accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('', views.loginPage, name='login'),
    path('register/', views.registerPage, name='register'),
    path('logout/', views.logoutUser, name='logout'),
    path('scoreboard/', views.scoreboard, name='scoreboard'),
]

game/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('stats/', views.stats, name='stats'),
]

wordle2/urls.py
from xml.etree.ElementInclude import include
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('game/', include('game.urls')),
    path('', include('accounts.urls'))
]

templates/base.html
{% load static %}

<html>

<head>

    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"
    /> 
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
 

    <title>{% block title %}{% endblock %}</title>
    

</head>

<body>
    <div class="container">
        {% block content %}
        {% endblock %}
        <script src="{% static 'js/main.js' %}"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
  

</body>

templates/home.html
{% extends 'base.html' %}

{% load static %}

{% block title %} Wordle Golf {% endblock %}

{% block content %}       
<div id="container">
    <div id="game">
        <a href="{% url 'accounts:logout' %}">Logout</a>
        <a href="{% url 'accounts:scoreboard' %}">Go To Scoreboard</a>
        <header>
            <h1 class="title">WORDLE GOLF</h1>
        </header>

        <div id="board-container">
            <div id="board"></div>
        </div>

        <div id="keyboard-container">
            <div class="keyboard-row">
            <button data-key="q">q</button>
            <button data-key="w">w</button>
            <button data-key="e">e</button>
            <button data-key="r">r</button>
            <button data-key="t">t</button>
            <button data-key="y">y</button>
            <button data-key="u">u</button>
            <button data-key="i">i</button>
            <button data-key="o">o</button>
            <button data-key="p">p</button>
            </div>
            <div class="keyboard-row">
            <div class="spacer-half"></div>
            <button data-key="a">a</button>
            <button data-key="s">s</button>
            <button data-key="d">d</button>
            <button data-key="f">f</button>
            <button data-key="g">g</button>
            <button data-key="h">h</button>
            <button data-key="j">j</button>
            <button data-key="k">k</button>
            <button data-key="l">l</button>
            <div class="spacer-half"></div>
            </div>
            <div class="keyboard-row">
            <button data-key="enter" class="wide-button">Enter</button>
            <button data-key="z">z</button>
            <button data-key="x">x</button>
            <button data-key="c">c</button>
            <button data-key="v">v</button>
            <button data-key="b">b</button>
            <button data-key="n">n</button>
            <button data-key="m">m</button>
            <button data-key="del" class="wide-button">Del</button>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    data_from_django = {{ todays_word|safe }};
    dictionary_from_django = {{ word_dictionary|safe }};
</script>
{% endblock %}

templates/scoreboard.html
{% extends 'base.html' %}

{% load static %}

{% block title %} Player Stats {% endblock %}

{% block content %}  

<table class="table table-condensed table-bordered">
    <thead>
        <tr class="success text-center">
            <th>Hole</th>
            <td>1</td>
            <td>2</td>
            <td>3</td>
            <td>4</td>
            <td>5</td>
            <td>6</td>
            <td>7</td>
            <td>8</td>
            <td>9</td>
            <td>10</td>
            <td>11</td>
            <td>12</td>
            <td>13</td>
            <td>14</td>
            <td>15</td>
            <td>16</td>
            <td>17</td>
            <td>18</td>
            <td>Total</td>
        </tr>
    </thead>
    <tbody>
        {% for users in scores %}
        <tr class="success text-center">
            {% for user in users %}
            <td>{{ user }}</td>
            {% endfor %}
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}